// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables (Non-blocking)
if (!SUPABASE_URL) {
  console.error('CRITICAL ERROR: Missing env.VITE_SUPABASE_URL. The app will likely fail to fetch data.');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('CRITICAL ERROR: Missing env.VITE_SUPABASE_PUBLISHABLE_KEY. The app will likely fail to fetch data.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use fallbacks to prevent crash during module initialization
const url = SUPABASE_URL || 'https://placeholder.supabase.co';
const key = SUPABASE_PUBLISHABLE_KEY || 'placeholder';

export const supabase = createClient<Database>(url, key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Test connection on initialization (optional - can be removed in production)
if (import.meta.env.DEV) {
  (async () => {
    try {
      const { error } = await supabase
        .from('profiles')
        .select('count')
        .limit(1);
      if (error) {
        console.warn('Supabase connection warning:', error.message);
      } else {
        console.log('✅ Conexão com o banco de dados Supabase estabelecida com sucesso!');
      }
    } catch (err) {
      console.error('❌ Erro ao conectar com o banco de dados:', err);
    }
  })();
}